version: '3'
services:
  app:
    container_name: atomic-design-samples
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: .
    volumes:
      - .:/home/app
      - node_modules_volume:/home/app/app/node_modules
    tty: true
    ports:
      - 3000:3000
    environment:
    - HOST=0.0.0.0
    - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_volume:
